name: Deploy React App to patate-mag (SFTP)

on:
  push:
    branches: ['*']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy via SFTP
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.SFTP_SERVER }}
          remote-user: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          protocol: sftp
          port: 22
          local-dir: ./build/
          remote-dir: /pat