name: Deploy via SFTP

on:
  push:
    branches: ['*']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy via Rsync
        uses: Burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: build/
          remote_path: /patate-mag
          remote_host: ${{ secrets.SFTP_SERVER }}
          remote_user: ${{ secrets.SFTP_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}