name: Deploy React App to patate-mag (SFTP)

on:
  push:
    branches: ['*']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SFTP_SERVER }}
          REMOTE_USER: ${{ secrets.SFTP_USER }}
          SOURCE: "build/"
          TARGET: "/patate-mag/"
          EXCLUDE: "/build/node_modules/, .git*, .env"