name: Test Deployment

on:
  push:
    branches:
      - 1-integrate-image-repositoring

jobs:
  test-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo
        run: echo "Test deployment success"
